"""Add trigger_type to Run model

Revision ID: 20d096e53f38
Revises: 888d2d4282fa
Create Date: 2025-11-25 09:49:21.799669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d096e53f38'
down_revision: Union[str, None] = '888d2d4282fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop unused index on match_score (wasn't being used for queries, cleanup)
    op.drop_index(op.f('ix_jobs_match_score'), table_name='jobs')
    # Add trigger_type field to track how runs are triggered (manual/scheduled)
    op.add_column('runs', sa.Column('trigger_type', sa.String(length=20), nullable=False, server_default='manual'))
    op.create_index(op.f('ix_runs_trigger_type'), 'runs', ['trigger_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_trigger_type'), table_name='runs')
    op.drop_column('runs', 'trigger_type')
    op.create_index(op.f('ix_jobs_match_score'), 'jobs', ['match_score'], unique=False)
    # ### end Alembic commands ###
