"""add_phone_cv_storage_custom_instructions_to_profile

Revision ID: ef8b8dca7d0d
Revises: 20d096e53f38
Create Date: 2025-11-25 13:59:12.073455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8b8dca7d0d'
down_revision: Union[str, None] = '20d096e53f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('cv_filename', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('cv_data', sa.LargeBinary(), nullable=True))
    op.add_column('user_profiles', sa.Column('custom_instructions', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('ai_generated_summary', sa.Text(), nullable=True))
    op.drop_column('user_profiles', 'cv_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('cv_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('user_profiles', 'ai_generated_summary')
    op.drop_column('user_profiles', 'custom_instructions')
    op.drop_column('user_profiles', 'cv_data')
    op.drop_column('user_profiles', 'cv_filename')
    op.drop_column('user_profiles', 'phone')
    # ### end Alembic commands ###
