"""Add logs field to runs table

Revision ID: 79ff1cda179f
Revises: 4ad0465d37bb
Create Date: 2025-11-24 20:51:12.486073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ff1cda179f'
down_revision: Union[str, None] = '4ad0465d37bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('logs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'logs')
    # ### end Alembic commands ###
