"""remove_profile_basic_info_and_cv_data

Revision ID: 69db4a40774f
Revises: g2b3c4d5e6f7
Create Date: 2025-12-07 18:45:45.673960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69db4a40774f'
down_revision: Union[str, None] = 'g2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_profiles_email'), 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'name')
    op.drop_column('user_profiles', 'rate')
    op.drop_column('user_profiles', 'phone')
    op.drop_column('user_profiles', 'email')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'linkedin')
    op.drop_column('user_profiles', 'cv_data')
    op.drop_column('user_profiles', 'github')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('github', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('cv_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('linkedin', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('rate', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_user_profiles_email'), 'user_profiles', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
